### ISSUE TITLE
Abnormal rendring

### ISSUE THREAD

**Issue by digital230** [CubeSugar/react-native-waveview#5]
if i set width of wave to 250 (in my case) then after 3sec waves end and show white background and after almost half sec starts new wave,

**Comment by digital230** [comment]
increasing T value in waveParams solve issue.

**Comment by Tojonirina4** [comment]
"increasing T value in waveParams solve issue."

Hello, 

Could you please provide the value of T that you use. For me it's 360 and still getting the issue

Thank you

**Comment by Tojonirina4** [comment]
Sorry, my bad. It was a padding
