### ISSUE TITLE
Wave display is cut when display the movement on a full phone screen width (tested on iphone 7plus)

### ISSUE THREAD

**Issue by Tojonirina4** [CubeSugar/react-native-waveview#8]
Hello,

When displaying the wave on a full screen (tested on  iphone 7plus) It seems that the continuation of the wave image is cut, interrupted. 

Could you please advise?

Thank you

**Comment by CubeSugar** [comment]
@Tojonirina4 

Could you show me some demo codes or some screenshot of test ? 

So I can fingure out workdarounds on v1.x and check this issue for next version (v2.0.0).

**Comment by Tojonirina4** [comment]
Hello,

Sorry, my bad. Caused by a padding on the container. Removed it and it's ok now :)

Closing the issue

**Comment by CubeSugar** [comment]
Glad to hear that u solve the issue. :)
